### ISSUE TITLE
Script wrongly detects some domains

### ISSUE THREAD

**Issue by hawkeye116477** [dead-hosts/KADhosts_git_azet12#1]
Welcome! I'd like to inform you that KAD has new owners => `https://github.com/PolishFiltersTeam`.
I'd like to inform you also that your script wrongly detects some domains, for example `pogotowie-komputerowe-warszawa.com.pl` is still registered. I assume that's probably, cuz it doesn't correctly extracts expiration date for that domains.
Anyway, now we have also our own script for detecting expired domains, so if you want, you can remove that repo :smile:.

**Comment by funilrys** [comment]
Hi @hawkeye116477, Did you reported it to Steven's hosts repository ?

Thanks for reporting. Actually  [PyFunceble](https://github.com/funilrys/PyFunceble) do more than "detecting expired domains" :wink: 

Will look into that more precisely.

Cheers,
Nissar
